apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortend-dep
  namespace: glamai-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-fortend
  template: 
    metadata:
      labels:
        app: cms-fortend
    spec:
      containers:
      - name: cms-fortend-container
        image: sarojdockerworkspace/glamai-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: cms-config
        env:
          - name: REACT_APP_API_BASE_URL 
            valueFrom:
              configMapKeyRef:
                name: cms-config
                key: REACT_APP_API_BASE_URL

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"