apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glamai-ingress
  namespace: glamai-ns
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://139.59.85.203.nip.io"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "139.59.85.203.nip.io"
    http:
      paths:
    
      - path: /server(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cms-svc
            port:
              number: 3000
      
      - path: /model(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cms-model-svc
            port:
              number: 3000
    
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cms-fortend-svc
            port:
              number: 80